SHELL := /bin/bash

# these files should pass pyflakes
PYFLAKES_WHITELIST=$(shell find . -name "*.py" ! -path "./doc/*" \
                    ! -path "./.tox/*" ! -path "*/compat.py" \
                    ! -path "*/build/*" ! -path "*/_*.py")

pyflakes:
	pyflakes ${PYFLAKES_WHITELIST}

pep:
	pep8 --first --exclude="_*,*build,*.tox" .

gitclean:
	git clean -Xfd

doc:
	rosrun rosdoc rosdoc $(shell ls -a | grep robair)

robair:
	roslaunch robair_app robair.launch

tv:
	roslaunch robair_app tv.launch

nxt:
	roslaunch robair_app nxt.launch
